"""Lesson 9.2: A Modelfile from the tokenizer

Do it

Run order inside this file:
1. Do it (source window 7)
2. Do it (source window 8)

Prerequisites: setup_prepare.
Use the existing rag-shell-venv interpreter; Run or Debug this file.
The functions below contain the lesson examples in source order. Helpers
supply configuration, authentication, state and CLI execution. See README.md
for expected observations, effects and the next file; GUIDE.md retains prose.
Example: open this file at the matching HTML heading, Run once, then inspect
the observations below before continuing to the next numbered section.
A successful process is not proof that a live result matched the sample.

"""
from workshop_helpers.session import DemoSession
from workshop_helpers.steps import manual_checkpoint, run_steps

# REPEAT replays the whole file; use only after reviewing its effects.
REPEAT = False
# A failed function may have partial effects. Inspect its saved attempt first.
RETRY_FAILED_STEP = False


# Original CLI workflow for step_01_a_modelfile_from_the_tokenizer.
COMMANDS_01 = """python3 -m venv ~/tf-venv && ~/tf-venv/bin/pip install -q "transformers==5.17.0" jinja2   # not the kit's pin: see below

"""

def step_01_a_modelfile_from_the_tokenizer(session):
    """Run Do it at this checkpoint.

    Do it

    Args: session is the active lesson run, with validated settings and saved prerequisites.
    Operations: bash — run in the operator shell (once: a venv with a transformers that can read the tokenizer).
    Returns: None; observations are printed or saved by the lesson code.
    Failures propagate to the session; inspect its failed attempt before continuing.

    Example: Run this file after its README prerequisites, or set a breakpoint in this function.
    Observe the printed/saved evidence for this heading; a zero exit alone is not proof.
    """
    # Preserve the kit CLI's arguments, conditions and observation order.
    session.shell(COMMANDS_01)

# Original CLI workflow for step_02_a_modelfile_from_the_tokenizer.
COMMANDS_02 = """cd services/slm && HF_HUB_DISABLE_PROGRESS_BARS=1 ~/tf-venv/bin/python make_modelfile.py --model unsloth/gemma-4-E2B-it --gguf documind-slm.gguf > ~/Modelfile.182
cd ../.. && cat ~/Modelfile.182

"""

def step_02_a_modelfile_from_the_tokenizer(session):
    """Run Do it at this checkpoint.

    Do it

    Args: session is the active lesson run, with validated settings and saved prerequisites.
    Operations: bash — run in the operator shell, in the kit (downloads the tokenizer's files, about 31 MB; no GPU, no Google Cloud).
    Returns: None; observations are printed or saved by the lesson code.
    Failures propagate to the session; inspect its failed attempt before continuing.

    Example: Run this file after its README prerequisites, or set a breakpoint in this function.
    Observe: [transformers] PyTorch was not found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
    # GENERATED by make_modelfile.py from the tokenizer. Do not hand-edit.
    # Regenerate whenever the checkpoint changes - the template belongs to the
    # weights, not to the project.

    FROM ./documind-slm.gguf

    TEMPLATE \"\"\"<bos><|turn>user
    {{ .Prompt }}<turn|>
    <|turn>model
    \"\"\"

    PARAMETER stop "<turn|>"

    PARAMETER num_ctx 4096
    """
    # Preserve the kit CLI's arguments, conditions and observation order.
    session.shell(COMMANDS_02)

def demonstrate(session):
    """Run this section in source order, saving each function's outcome.

    Example: main() opens the configured session and calls demonstrate(session).
    A failed step stops this sequence; inspect its evidence before an explicit retry.
    """
    run_steps(session, [
        ('source_7', step_01_a_modelfile_from_the_tokenizer),
        ('source_8', step_02_a_modelfile_from_the_tokenizer),
    ], retry_failed=RETRY_FAILED_STEP, cleanup=False, finalize=False)


def main():
    """Open the lesson session and run this section.

    Example: use Run/Debug on this file with the rag-shell-venv interpreter.
    Project settings and completed prerequisites come from the shared setup.
    """
    with DemoSession(__file__, live=True, repeat=REPEAT) as session:
        demonstrate(session)


if __name__ == "__main__":
    main()
