#!/usr/bin/env python3
"""Generate the Modelfile FROM THE TOKENIZER. Owned by lesson 11.4.

This exists because the alternative - typing a TEMPLATE from a blog post - is the
single most common way a working fine-tune looks broken. The weights learned one
turn format; the runtime is told another; the model answers fluently and never
stops, and you spend an afternoon re-reading your training data.

    python make_modelfile.py --model ./documind-slm --gguf documind-slm.gguf > Modelfile
"""
import argparse
import sys


def build(chat_template: str, stops: list[str], gguf: str, num_ctx: int = 4096) -> str:
    lines = [
        "# GENERATED by make_modelfile.py from the tokenizer. Do not hand-edit.",
        "# Regenerate whenever the checkpoint changes - the template belongs to the",
        "# weights, not to the project.",
        "",
        f"FROM ./{gguf}",
        "",
        'TEMPLATE """' + chat_template + '"""',
        "",
    ]
    lines += [f'PARAMETER stop "{s}"' for s in stops]
    lines += ["", f"PARAMETER num_ctx {num_ctx}"]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", required=True, help="path or hub id of the tuned model")
    ap.add_argument("--gguf", default="documind-slm.gguf")
    ap.add_argument("--num-ctx", type=int, default=4096)
    args = ap.parse_args()

    from transformers import AutoTokenizer
    tok = AutoTokenizer.from_pretrained(args.model)

    if not tok.chat_template:
        print("this tokenizer has no chat_template - refusing to invent one",
              file=sys.stderr)
        return 2

    # Ollama's TEMPLATE is Go templating; a Jinja chat_template is not a drop-in.
    # Render the turn structure once and translate the two placeholders, which is
    # all Ollama needs for a single-turn instruct model.
    rendered = tok.apply_chat_template(
        [{"role": "user", "content": "__PROMPT__"}],
        tokenize=False, add_generation_prompt=True)
    template = rendered.replace("__PROMPT__", "{{ .Prompt }}")

    # The stop tokens ARE the special tokens the model was trained to emit. Take
    # them from the tokenizer; do not guess which angle brackets it uses.
    stops = [t for t in (tok.eos_token, getattr(tok, "eot_token", None)) if t]
    for extra in tok.all_special_tokens:
        if "end" in extra.lower() or "return" in extra.lower():
            stops.append(extra)
    stops = list(dict.fromkeys(stops))

    sys.stdout.write(build(template, stops, args.gguf, args.num_ctx))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
