"""deploy/INDEX.md: every file in the kit, and the workshop lessons that show it.

    python tools/kit_index.py            # rewrite deploy/INDEX.md
    python tools/kit_index.py --check    # exit 1 if deploy/INDEX.md is stale (CI)

For each file git tracks under deploy/: its kind, the lessons whose pages quote it (a read-only window
labelled with its path, checked verbatim by pagekit/check_lesson.py), and the lessons that name it elsewhere
on the page. A file no lesson shows yet is listed too, so the index doubles as the map of what the workshop
has not explained. The output is deterministic: no dates, sorted rows.
"""
from __future__ import annotations

import html
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from pagekit.pagebuild import KIT, MANIFEST, page_path  # noqa: E402

INDEX = KIT / "INDEX.md"
TAG = re.compile(r"<[^>]+>")
CODE_EXT = {".py", ".sh", ".tf", ".mk", ".sql", ".js", ".ts", ".hcl"}
CONFIG_EXT = {".yaml", ".yml", ".toml", ".cfg", ".ini", ".txt", ".json"}
DATA_EXT = {".jsonl", ".csv", ".png", ".jpg", ".jpeg", ".gif", ".pdf", ".mp3", ".mp4", ".wav"}


def kit_files() -> list[str]:
    try:
        out = subprocess.run(["git", "ls-files", "-z", "--", "deploy"], cwd=str(ROOT), capture_output=True, check=True).stdout
        files = sorted(p[len("deploy/"):] for p in out.decode("utf-8").split("\0") if p.startswith("deploy/"))
    except (OSError, subprocess.CalledProcessError):
        files = []
    if files:
        return files
    skip = {"__pycache__", ".pytest_cache", ".terraform"}
    return sorted(p.relative_to(KIT).as_posix() for p in KIT.rglob("*")
                  if p.is_file() and not skip.intersection(p.parts) and p.suffix != ".pyc")


def kind(rel: str) -> str:
    name = rel.rsplit("/", 1)[-1]
    suffix = ("." + name.rsplit(".", 1)[-1].lower()) if "." in name else ""
    if rel.startswith(("evals/corpus/", "evals/demo/", "evals/sft/")) or suffix in DATA_EXT:
        return "data"
    if name in ("Makefile",) or name.startswith("Dockerfile") or suffix in CODE_EXT:
        return "code"
    if suffix == ".md":
        return "doc"
    if suffix in CONFIG_EXT or name.startswith("."):
        return "config"
    return "other"


def authored() -> list[str]:
    return [lid for m in MANIFEST["modules"].values() for lid, les in m["lessons"].items()
            if les.get("slug") and les.get("topic_filename") and page_path(lid).exists()]


NOT_EXCERPTS = ("bash", "shell", "python", "text", "log", "json", "output", "expected", "gcloud", "make")


def usage(files: list[str]) -> tuple[dict, dict]:
    """quoted[f]: lessons with a read-only excerpt window labelled with f; named[f]: lessons that name f otherwise."""
    quoted = {f: [] for f in files}
    named = {f: [] for f in files}
    # a path counts whole: "validate.py" is not found inside "commands/validate.py"; a "deploy/" prefix is allowed
    rxs = {f: re.compile(r"(?<![\w/.-])(?:deploy/)?" + re.escape(f) + r"(?![\w/-])") for f in files}
    for lid in authored():
        page = page_path(lid).read_text(encoding="utf-8")
        labels = [html.unescape(TAG.sub("", m)).strip() for m in
                  re.findall(r'<div class="cw"><div class="ch-bar"><span>(.*?)</span>', page, re.S)]
        excerpt_labels = [label for label in labels if not label.lower().startswith(NOT_EXCERPTS)]
        text = html.unescape(TAG.sub(" ", page))
        for f, rx in rxs.items():
            # Most lesson-demo paths never appear in a page. A literal rejection
            # is equivalent to a failed path regex and avoids rescanning every
            # large HTML page for hundreds of new, unmentioned entry points.
            if f not in text and not any(f in label for label in excerpt_labels):
                continue
            if any(rx.search(label) for label in excerpt_labels):
                quoted[f].append(lid)
            elif rx.search(text):
                named[f].append(lid)
    return quoted, named


def render() -> str:
    files = kit_files()
    quoted, named = usage(files)
    shown = sum(1 for f in files if quoted[f] or named[f])
    lines = [
        "# INDEX - every kit file, and the lessons that show it",
        "",
        "Generated by `tools/kit_index.py` in the authoring repository; do not edit by hand.",
        "**Quoted in**: a lesson page shows the file's code in a read-only window, checked verbatim against this",
        "tree on every pull request. **Named in**: a lesson page names the file (a command, a path, a pointer).",
        "Lesson numbers are the Agents Workshop's (course-manifest.json). A file with neither is not yet explained",
        "by a lesson; its own docstring, README.md and UNOWNED.md are where it is described.",
        "",
        f"{len(files)} files; {sum(1 for f in files if quoted[f])} quoted by a lesson, {shown} shown or named by one.",
        "",
        "| File | Kind | Quoted in | Named in |",
        "|---|---|---|---|",
    ]
    for f in files:
        lines.append(f"| `{f}` | {kind(f)} | {', '.join(quoted[f]) or '-'} | {', '.join(named[f]) or '-'} |")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    text = render()
    if argv == ["--check"]:
        current = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
        if current != text:
            print("deploy/INDEX.md is stale: run python tools/kit_index.py", file=sys.stderr)
            return 1
        print("deploy/INDEX.md is current")
        return 0
    INDEX.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote deploy/INDEX.md: {text.count(chr(10)) - 12} files")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
